### ISSUE TITLE
How to obtain the recommended contour level?

### ISSUE THREAD

**Issue by yinjunbo** [BioinfoMachineLearning/cryo2struct#2]
Hi, thanks for your dataset!
I'm wondering how to obtain an ideal contour level for each map?

**Comment by nabingiri** [comment]
Step 1: Go to webpage: https://www.emdataresource.org/?
Step 2: On top right of the website there is a search button. Enter cryo-EM density map name, example: 25855
Step 3: Once you press search, another tab opens which contains information about the density map 25855
Step 4: Go to "Map" on this webpage and you will find the recommended contour level.
